version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on: 
      - backend
    ports: 
      - "5173:5173"
    volumes:
      - .:/home/pigeon
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - redis
    ports:
       - "2000:2000"
    volumes:
      - .:/home/pigeon
    environment: 
    # print directly to terminal
      - PYTHONUNBUFFERED=1
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    depends_on:
      - postgresdb
    ports:
      - "6379:6379"
    volumes:
      - .:/home/pigeon
  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pigeondb