[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["server_tests/"]
filterwarnings = []


[tool.pyright]
exclude = ["**/node_modules", "**/__pycache__", "**/venv"]
reportMissingImports = true
reportMissingTypeStubs = false
pythonVersion = "3.12"
pythonPlatform = "Linux"
executionEnvironments = [{ root = "." }]


[tool.ruff]
target-version = "py38"


[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # pep8-naming
    "N",
    # pydocstyle
    "D",
]


[tool.ruff.lint.per-file-ignores]
# D415: API endpoint docstrings shouldn't end with a period
"server/controllers/*" = ["D415"]
"server_tests/*" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"
