version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspaces/pigeon:cached

    command: sleep infinity

    # Runs app on the same network as database and redis, allowing forwardPorts to work in devcontainer.json
    networks:
      - backend

  redis:
    image: redis-stack-server:7.2.0-v6
    ports:
      - "6379:6379"
    volumes:
      - db-data:/data
    networks:
      - backend

  database:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pigeondb
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
