version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/pigeon:cached
    command: sleep infinity
    networks:
      - backend

  redis:
    image: redis/redis-stack-server:7.2.0-v6
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - data:/home/pigeon
    networks:
      - backend

  redis-test:
    image: redis/redis-stack-server:7.2.0-v6
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - data:/home/pigeon
    networks:
      - backend

  database:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pigeondb
    networks:
      - backend

volumes:
  data:

networks:
  backend:
    driver: bridge
